// <auto-generated />
namespace AssessmentNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class alpha1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alpha1));
        
        string IMigrationMetadata.Id
        {
            get { return "201401121058154_alpha1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
